package com.example.a36_retrofit.domain.detailsDomain.model

import com.example.a36_retrofit.data.database.entities.MovieDetailsEntity
import com.example.a36_retrofit.data.network.model.*

data class MovieDetailsItem(
    val adult: Boolean,
    val backdrop_path: String,
    val belongs_to_collection: BelongsToCollection?=null,
    val budget: Int,
    val genres: List<Genre>?=null,
    val homepage: String,
    val id: Int,
    val imdb_id: String,
    val original_language: String,
    val original_title: String,
    val overview: String,
    val popularity: Double,
    val poster_path: String,
    val production_companies: List<ProductionCompany>?=null,
    val production_countries: List<ProductionCountry>?=null,
    val release_date: String,
    val revenue: Int,
    val runtime: Int,
    val spoken_languages: List<SpokenLanguage>?=null,
    val status: String,
    val tagline: String,
    val title: String,
    val video: Boolean,
    val vote_average: Double,
    val vote_count: Int
)

fun MovieById.toDomain()=MovieDetailsItem(
 adult,
 backdrop_path,
 belongs_to_collection,
 budget,
 genres,
 homepage,
 id,
 imdb_id,
 original_language,
 original_title,
 overview,
 popularity,
poster_path,
 production_companies,
 production_countries,
 release_date,
 revenue,
 runtime,
 spoken_languages,
 status,
 tagline,
 title,
 video,
 vote_average,
 vote_count)

fun MovieDetailsEntity.toDomain()=MovieDetailsItem(
    adult=adult,
    backdrop_path= backdrop_path,
//    belongs_to_collection=belongs_to_collection,
    budget=budget,
//    genres,
    homepage=    homepage,
    id=id,
    imdb_id=imdb_id,
    original_language=original_language,
    original_title=original_title,
    overview=overview,
    popularity=popularity,
    poster_path=poster_path,
//    production_companies,
//    production_countries,
    release_date=release_date,
    revenue=revenue,
    runtime=runtime,
//    spoken_languages,
    status=status,
    tagline=tagline,
    title=title,
    video=video,
    vote_average=vote_average,
    vote_count=vote_count)